packages:
    - "examples/*"
    - "termost"
allowBuilds:
    unrs-resolver: false
minimumReleaseAgeExclude:
    - "@adbayb/stack"
    - quickbundle
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*eslint*"
    - "*prettier*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
