name: Continous delivery

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    integrate:
        uses: ./.github/workflows/workflow.yml
    release:
        timeout-minutes: 5
        needs: integrate
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
            pull-requests: write
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - uses: pnpm/action-setup@v6
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  cache: pnpm
                  node-version-file: "package.json"
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Create release pull request or Publish stable version(s)
              id: changesets
              uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1 # v2.1.1
              with:
                  commit-message: "chore: release package(s)"
                  create-github-releases: true
                  pr-title: "chore: release package(s)"
                  publish-script: pnpm release:publish
                  version-script: pnpm release:version
            - name: Publish snapshot version(s)
              if: steps.changesets.outputs.published == 'false' && steps.changesets.outputs.has-changesets == 'true'
              run: |
                  git stash # To avoid being affected by changes made in the previous step, including the removal of changeset files that could lead to errors.
                  pnpm release:snapshot
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
