name: Continuous Integration

on:
    push:

jobs:
    install:
        timeout-minutes: 5
        name: Install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - name: Get node version
              run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
              id: node
            - name: Setup node ${{ steps.node.outputs.version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.node.outputs.version }}
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install
    check:
        timeout-minutes: 5
        needs: install
        name: Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - name: Get node version
              run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
              id: node
            - name: Setup node ${{ steps.node.outputs.version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.node.outputs.version }}
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Check (lint, test, types)
              run: pnpm check
    build:
        timeout-minutes: 5
        needs: install
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - name: Get node version
              run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
              id: node
            - name: Setup node ${{ steps.node.outputs.version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.node.outputs.version }}
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
