name: Continuous Integration

on:
    push:

jobs:
    install:
        timeout-minutes: 5
        name: Install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - name: Get node version
              run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
              id: node
            - name: Setup node ${{ steps.node.outputs.version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.node.outputs.version }}
                  cache: pnpm
            - name: Setup cache
              id: cache
              uses: actions/cache@v3
              with:
                  path: |
                      ./node_modules
                      ./turbo
                  key: ${{ runner.os }}-cache-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-cache-
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
    build:
        timeout-minutes: 5
        needs: install
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - name: Get node version
              run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
              id: node
            - name: Setup node ${{ steps.node.outputs.version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.node.outputs.version }}
                  cache: pnpm
            - name: Setup cache
              id: cache
              uses: actions/cache@v3
              with:
                  path: |
                      ./node_modules
                      ./turbo
                  key: ${{ runner.os }}-cache-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-cache-
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Build
              run: pnpm build
    check:
        timeout-minutes: 5
        needs: build
        name: Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - name: Get node version
              run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
              id: node
            - name: Setup node ${{ steps.node.outputs.version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.node.outputs.version }}
                  cache: pnpm
            - name: Setup cache
              id: cache
              uses: actions/cache@v3
              with:
                  path: |
                      ./node_modules
                      ./turbo
                  key: ${{ runner.os }}-cache-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-cache-
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Check (static analysis including linters, types, and commit message)
              run: pnpm check
    test:
        timeout-minutes: 5
        needs: build
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - name: Get node version
              run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
              id: node
            - name: Setup node ${{ steps.node.outputs.version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.node.outputs.version }}
                  cache: pnpm
            - name: Setup cache
              id: cache
              uses: actions/cache@v3
              with:
                  path: |
                      ./node_modules
                      ./turbo
                  key: ${{ runner.os }}-cache-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-cache-
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Check (code execution)
              run: pnpm test
